# SPDX-FileCopyrightText: Copyright (c) Yegor Bugayenko, 2025
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
    "vale-styles/proselint/Nonwords.yml",
    "vale-styles/proselint/Needless.yml",
    "vale-styles/proselint/Cliches.yml",
    "vale-styles/Google/Ordinal.yml",
    "vale-styles/proselint/Archaisms.yml",
    "vale-styles/Microsoft/Avoid.yml"
]
